#!/usr/bin/env node
/* global process, console */
/* eslint-disable no-console */
// Records a single command run via node-pty and writes a terminalizer-compatible YAML.
// Usage: node packages/quality-gate/preview/record.mjs <name> <argv-json>
// Example:
//   node packages/quality-gate/preview/record.mjs dry-run '["node","packages/quality-gate/dist/precommit.js","--dry-run"]'

import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const ptyPath = resolve(
    dirname(fileURLToPath(import.meta.url)),
    '../../..',
    'node_modules/.pnpm/@homebridge+node-pty-prebuilt-multiarch@0.11.14/node_modules/@homebridge/node-pty-prebuilt-multiarch',
)
const pty = require(ptyPath)

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '../../..')

const [, , name] = process.argv
const PRESETS = {
    'dry-run': [process.execPath, 'packages/quality-gate/dist/precommit.js', '--dry-run'],
    error: [process.execPath, 'packages/quality-gate/dist/precommit.js', '--dry-run-fail'],
}
if (!name || !PRESETS[name]) {
    console.error(`usage: record.mjs <${Object.keys(PRESETS).join('|')}>`)
    process.exit(2)
}
const argv = PRESETS[name]

const cols = 70
const rows = 22

const ptyProcess = pty.spawn(argv[0], argv.slice(1), {
    name: 'xterm-256color',
    cols,
    rows,
    cwd: repoRoot,
    env: { ...process.env, FORCE_COLOR: '1' },
})

const records = []
let lastTime = Date.now()
let firstChunk = true

ptyProcess.onData((data) => {
    const now = Date.now()
    const delay = firstChunk ? 0 : now - lastTime
    firstChunk = false
    lastTime = now
    records.push({ delay, content: data })
    process.stdout.write(data)
})

ptyProcess.onExit(({ exitCode }) => {
    // Hold the last frame visible for a moment by extending the previous frame's delay.
    if (records.length > 0) records[records.length - 1].delay += 1500

    const yml = renderYaml({
        records,
        config: {
            cols,
            rows,
            command: argv.join(' '),
        },
    })
    const outFile = resolve(here, `${name}.yml`)
    writeFileSync(outFile, yml)
    console.error(`\n[record.mjs] wrote ${outFile} (${records.length} frames, exit=${exitCode})`)
    process.exit(0)
})

function yamlString(s) {
    // Use single-line double-quoted string with escapes; terminalizer accepts standard YAML.
    return JSON.stringify(s)
}

function renderYaml({ records, config }) {
    const lines = []
    lines.push(`# Auto-generated by record.mjs`)
    lines.push(`config:`)
    lines.push(`  command: ${yamlString(config.command)}`)
    lines.push(`  cwd: null`)
    lines.push(`  env:`)
    lines.push(`    recording: "true"`)
    lines.push(`  cols: ${config.cols}`)
    lines.push(`  rows: ${config.rows}`)
    lines.push(`  repeat: 0`)
    lines.push(`  quality: 100`)
    lines.push(`  frameDelay: auto`)
    lines.push(`  maxIdleTime: 1500`)
    lines.push(`  frameBox:`)
    lines.push(`    type: floating`)
    lines.push(`    title: AgentILS Quality Gate`)
    lines.push(`    style:`)
    lines.push(`      border: 0px black solid`)
    lines.push(`      margin: 0`)
    lines.push(`      padding: 8px`)
    lines.push(`      backgroundColor: "#0b1220"`)
    lines.push(`  watermark:`)
    lines.push(`    imagePath: null`)
    lines.push(`    style:`)
    lines.push(`      position: absolute`)
    lines.push(`      right: 15px`)
    lines.push(`      bottom: 15px`)
    lines.push(`      width: 100px`)
    lines.push(`      opacity: 0.9`)
    lines.push(`  cursorStyle: block`)
    lines.push(`  fontFamily: "Cascadia Mono PL, Consolas, Monaco, Lucida Console, monospace"`)
    lines.push(`  fontSize: 14`)
    lines.push(`  lineHeight: 1.0`)
    lines.push(`  letterSpacing: 0`)
    lines.push(`  theme:`)
    lines.push(`    background: "transparent"`)
    lines.push(`    foreground: "#e6edf3"`)
    lines.push(`    cursor: "#c9d1d9"`)
    lines.push(`    black: "#0b1220"`)
    lines.push(`    red: "#f85149"`)
    lines.push(`    green: "#3fb950"`)
    lines.push(`    yellow: "#d29922"`)
    lines.push(`    blue: "#58a6ff"`)
    lines.push(`    magenta: "#bc8cff"`)
    lines.push(`    cyan: "#39c5cf"`)
    lines.push(`    white: "#e6edf3"`)
    lines.push(`    brightBlack: "#6e7681"`)
    lines.push(`    brightRed: "#ff7b72"`)
    lines.push(`    brightGreen: "#56d364"`)
    lines.push(`    brightYellow: "#e3b341"`)
    lines.push(`    brightBlue: "#79c0ff"`)
    lines.push(`    brightMagenta: "#d2a8ff"`)
    lines.push(`    brightCyan: "#56d4dd"`)
    lines.push(`    brightWhite: "#f0f6fc"`)
    lines.push(`records:`)
    for (const r of records) {
        lines.push(`  - delay: ${r.delay}`)
        lines.push(`    content: ${yamlString(r.content)}`)
    }
    return lines.join('\n') + '\n'
}
