export const RULE_CATEGORIES = [
    'guidance-only',
    'pre-tool enforcement',
    'stop enforcement',
    'subagent-stop enforcement',
    'ci enforcement',
    'git-hook enforcement',
    'manual-review',
]

export const RULE_DISCOVERY_SOURCES = [
    'README.md',
    'README.zh-CN.md',
    'docs/instructions/agentils.instructions.md',
    'docs/instructions/webview-source-of-truth.instructions.md',
    'docs/skills/instructions-sync-discipline/SKILL.md',
    'docs/skills/branch-name-standard/SKILL.md',
    'docs/agents/ralph-product.md',
    'docs/agents/ralph-developer.md',
    'docs/agents/ralph-ops.md',
    'docs/agents/ralph-contributor.md',
    'docs/agents/ralph-tester.md',
    'docs/agents/ralph-beta.md',
    '.github/workflows/ci.yml',
    'agentils-gate.config.mjs',
    'scripts/dev/check-branch-for-prd.mjs',
]

export const RULE_REGISTRY = [
    {
        id: 'agent.generated-targets.edit-source-only',
        title: 'Generated agent targets must be edited via docs sources',
        category: 'pre-tool enforcement',
        currentType: 'runtime-enforced',
        sourceDocument: 'docs/skills/instructions-sync-discipline/SKILL.md',
        originalGuidance:
            'Always edit the source under docs/ and run the sync script; never hand-edit the generated targets.',
        enforcementLevel: 'deny',
        enforcementPhase: 'pre-tool',
        enforcementTarget: 'runtime-pre-tool',
        requiredCapabilitiesAll: ['runtime-pre-tool'],
        requiredCapabilitiesAny: ['write-targets', 'command-text', 'patch-text'],
        checkStrategy: {
            kind: 'protected-write-target',
            repoFiles: ['AGENTS.md', 'CLAUDE.md', '.github/copilot-instructions.md'],
            repoDirs: [
                '.github/instructions',
                '.github/skills',
                '.github/agents',
                '.agents/skills',
                '.claude/skills',
                '.claude/agents',
                '.codex/agents',
            ],
            commandHints: [
                '.github/instructions/',
                '.github/skills/',
                '.github/agents/',
                '.agents/skills/',
                '.claude/skills/',
                '.claude/agents/',
                '.codex/agents/',
                '.github/copilot-instructions.md',
                'AGENTS.md',
                'CLAUDE.md',
            ],
        },
        failureMessage: 'Repository policy blocks direct edits to generated agent targets.',
        fixHint: 'Edit the corresponding file under docs/ and run `pnpm run sync:instructions`.',
        currentStatus: 'enforced',
    },
    {
        id: 'agent.private-memory.no-persistent-repo-rules',
        title: 'Repository rules must not be written into private memories or local rule files',
        category: 'pre-tool enforcement',
        currentType: 'runtime-enforced',
        sourceDocument: 'docs/instructions/agentils.instructions.md',
        originalGuidance:
            '共享 hook 脚本 `scripts/agent-hooks/policy.mjs` 会阻止 agent 直接写 `~/.codex/memories/**`、`~/.claude/projects/*/memory/**`、`.claude/settings.local.json` 以及各类生成型 agent 目标文件。',
        enforcementLevel: 'deny',
        enforcementPhase: 'pre-tool',
        enforcementTarget: 'runtime-pre-tool',
        requiredCapabilitiesAll: ['runtime-pre-tool'],
        requiredCapabilitiesAny: ['write-targets', 'command-text', 'patch-text'],
        checkStrategy: {
            kind: 'protected-write-target',
            repoFiles: ['.claude/settings.local.json', '.cursorrules', '.clinerules'],
            homePathPatterns: [
                { base: '~/.codex/memories', label: '~/.codex/memories/' },
                {
                    base: '~/.claude/projects',
                    contains: '/memory/',
                    label: '~/.claude/projects/.../memory/',
                },
            ],
            commandHints: [
                '.claude/settings.local.json',
                '.cursorrules',
                '.clinerules',
                '~/.codex/memories/',
                '$HOME/.codex/memories/',
                '~/.claude/projects/',
                '$HOME/.claude/projects/',
            ],
        },
        failureMessage: 'Repository policy blocks writes to private memory stores or local-only rule files.',
        fixHint: 'Persist repo rules in tracked docs instead of private memory or local config.',
        currentStatus: 'enforced',
    },
    {
        id: 'git.hook-bypass.forbidden',
        title: 'Git hooks and memory guards must not be bypassed',
        category: 'pre-tool enforcement',
        currentType: 'runtime-enforced',
        sourceDocument: 'docs/instructions/agentils.instructions.md',
        originalGuidance:
            '不允许使用 `--no-verify` / `git -c core.hooksPath=/dev/null` / `HUSKY=0` 等任何形式绕过 hook。',
        enforcementLevel: 'deny',
        enforcementPhase: 'pre-tool',
        enforcementTarget: 'runtime-pre-tool',
        requiredCapabilitiesAll: ['runtime-pre-tool', 'command-text'],
        checkStrategy: { kind: 'command-pattern', patternSet: 'hook-bypass' },
        failureMessage: 'Repository policy blocks bypassing git hooks or agent memory guards.',
        fixHint: 'Run the command without bypass flags and let hooks or CI evaluate the change normally.',
        currentStatus: 'enforced',
    },
    {
        id: 'instructions.generated-targets.require-source-change',
        title: 'Generated targets cannot drift without matching source updates',
        category: 'stop enforcement',
        currentType: 'runtime-enforced',
        sourceDocument: 'docs/skills/instructions-sync-discipline/SKILL.md',
        originalGuidance:
            'Commit the source file **and** the regenerated targets together. Never split them across commits.',
        enforcementLevel: 'block',
        enforcementPhase: 'stop',
        enforcementTarget: 'runtime-stop',
        requiredCapabilitiesAll: ['runtime-stop', 'dirty-files'],
        checkStrategy: { kind: 'instruction-sync', mode: 'generated-targets-require-source' },
        failureMessage: 'Generated agent targets changed without matching source updates.',
        fixHint: 'Edit the docs source and re-run `pnpm run sync:instructions` before finishing.',
        currentStatus: 'enforced',
    },
    {
        id: 'instructions.sync.required-before-stop',
        title: 'Instruction source changes must be synced before the agent finishes',
        category: 'stop enforcement',
        currentType: 'runtime-enforced',
        sourceDocument: 'docs/instructions/agentils.instructions.md',
        originalGuidance:
            '**Stop**：当 instruction source 改了但 `sync:instructions` 未通过、或 generated target 漂移、或中英 README 只改一边时，阻止 agent 结束。',
        enforcementLevel: 'block',
        enforcementPhase: 'stop',
        enforcementTarget: 'runtime-stop',
        requiredCapabilitiesAll: ['runtime-stop', 'dirty-files', 'instructions-sync-status'],
        checkStrategy: { kind: 'instruction-sync', mode: 'source-changes-require-sync' },
        failureMessage: 'Instruction sources changed but generated targets are out of sync.',
        fixHint:
            'Run `pnpm run sync:instructions` and verify `node scripts/dev/sync-agent-instructions.mjs --check` passes.',
        currentStatus: 'enforced',
    },
    {
        id: 'docs.readme-pair.sync-required',
        title: 'Bilingual README pairs must be updated together',
        category: 'stop enforcement',
        currentType: 'runtime-enforced',
        sourceDocument: 'docs/instructions/agentils.instructions.md',
        originalGuidance:
            '改 `xxx.md` 的同时必须改 `xxx.zh-CN.md`（反之亦然）。新加段落必须在两份里都加。**禁止只改一份就提交**。',
        enforcementLevel: 'block',
        enforcementPhase: 'stop',
        enforcementTarget: 'runtime-stop',
        requiredCapabilitiesAll: ['runtime-stop', 'dirty-files'],
        checkStrategy: { kind: 'readme-pair', source: 'dirty-files' },
        failureMessage: 'README bilingual pairs changed on only one side.',
        fixHint: 'Update the matching `README.md` or `README.zh-CN.md` file in the same directory.',
        currentStatus: 'enforced',
    },
    {
        id: 'subagent.product.read-only-scope',
        title: 'Ralph product may only edit run metadata files',
        category: 'subagent-stop enforcement',
        currentType: 'runtime-enforced',
        sourceDocument: 'docs/agents/ralph-product.md',
        originalGuidance: 'Do not modify source files.',
        enforcementLevel: 'block',
        enforcementPhase: 'subagent-stop',
        enforcementTarget: 'subagent-stop',
        applicableRuntime: ['subagent'],
        requiredCapabilitiesAll: ['subagent-stop', 'changed-files', 'subagent-role'],
        checkStrategy: {
            kind: 'subagent-role-allowlist',
            role: 'product',
            allowedPatterns: ['{RUN_DIR}/prd.json', '{RUN_DIR}/progress.txt', '{RUN_DIR}/handoff/product.md'],
        },
        failureMessage: 'Ralph product touched files outside the allowed read-only run metadata scope.',
        fixHint: 'Keep product changes inside the run handoff files and PRD metadata only.',
        currentStatus: 'enforced',
    },
    {
        id: 'subagent.ops.ci-only-scope',
        title: 'Ralph ops may only edit CI or release config plus its own handoff',
        category: 'subagent-stop enforcement',
        currentType: 'runtime-enforced',
        sourceDocument: 'docs/agents/ralph-ops.md',
        originalGuidance: 'Only update CI/release configuration; do not modify source code.',
        enforcementLevel: 'block',
        enforcementPhase: 'subagent-stop',
        enforcementTarget: 'subagent-stop',
        applicableRuntime: ['subagent'],
        requiredCapabilitiesAll: ['subagent-stop', 'changed-files', 'subagent-role'],
        checkStrategy: {
            kind: 'subagent-role-allowlist',
            role: 'ops',
            allowedPatterns: [
                '{RUN_DIR}/prd.json',
                '{RUN_DIR}/progress.txt',
                '{RUN_DIR}/handoff/ops.md',
                '.github/workflows/*.yml',
                '.changeset/*',
                '.changeset/config.json',
                'packages/logger-collector/.goreleaser.yml',
            ],
        },
        failureMessage: 'Ralph ops touched files outside CI or release configuration scope.',
        fixHint: 'Limit ops changes to workflows, release config, changesets, and its own run handoff.',
        currentStatus: 'enforced',
    },
    {
        id: 'subagent.contributor.docs-only-scope',
        title: 'Ralph contributor may only edit documentation surfaces',
        category: 'subagent-stop enforcement',
        currentType: 'runtime-enforced',
        sourceDocument: 'docs/agents/ralph-contributor.md',
        originalGuidance: 'Only modify documentation files (README, CHANGELOG, instructions, CLAUDE.md, etc.).',
        enforcementLevel: 'block',
        enforcementPhase: 'subagent-stop',
        enforcementTarget: 'subagent-stop',
        applicableRuntime: ['subagent'],
        requiredCapabilitiesAll: ['subagent-stop', 'changed-files', 'subagent-role'],
        checkStrategy: {
            kind: 'subagent-role-allowlist',
            role: 'contributor',
            allowedPatterns: [
                '{RUN_DIR}/prd.json',
                '{RUN_DIR}/progress.txt',
                '{RUN_DIR}/handoff/contributor.md',
                'README.md',
                'README.zh-CN.md',
                'CHANGELOG*',
                'CLAUDE.md',
                'docs/**/*.md',
                '.github/instructions/*.md',
                '*.instructions.md',
                'packages/*/README.md',
                'packages/*/README.zh-CN.md',
                'packages/*/CHANGELOG.md',
                'packages/*/CHANGELOG*.md',
            ],
        },
        failureMessage: 'Ralph contributor touched files outside documentation scope.',
        fixHint: 'Keep contributor changes limited to docs, instructions, changelogs, and its own run handoff.',
        currentStatus: 'enforced',
    },
    {
        id: 'subagent.handoff.owner-only',
        title: 'Each Ralph role may only write its own handoff file',
        category: 'subagent-stop enforcement',
        currentType: 'runtime-enforced',
        sourceDocument: 'docs/agents/ralph-developer.md',
        originalGuidance: 'Do not update tester handoff; write only `{RUN_DIR}/handoff/developer.md`.',
        enforcementLevel: 'block',
        enforcementPhase: 'subagent-stop',
        enforcementTarget: 'subagent-stop',
        applicableRuntime: ['subagent'],
        requiredCapabilitiesAll: ['subagent-stop', 'changed-files', 'subagent-role'],
        checkStrategy: { kind: 'subagent-owned-handoff' },
        failureMessage: 'A Ralph subagent modified another role’s handoff file.',
        fixHint: 'Write only the current role’s handoff file under the active run directory.',
        currentStatus: 'enforced',
    },
    {
        id: 'ci.readme-pair.sync-required',
        title: 'CI must reject PRs that change only one side of a bilingual README pair',
        category: 'ci enforcement',
        currentType: 'repository-enforced',
        sourceDocument: 'docs/instructions/agentils.instructions.md',
        originalGuidance:
            '改 `xxx.md` 的同时必须改 `xxx.zh-CN.md`（反之亦然）。新加段落必须在两份里都加。**禁止只改一份就提交**。',
        enforcementLevel: 'block',
        enforcementPhase: 'ci',
        enforcementTarget: 'repository-ci',
        applicableRuntime: ['repository'],
        requiredCapabilitiesAll: ['repository-ci', 'changed-files'],
        checkStrategy: { kind: 'readme-pair', source: 'changed-files' },
        failureMessage: 'CI detected a README bilingual pair updated on only one side.',
        fixHint: 'Include the matching `README.md` or `README.zh-CN.md` file in the same change set.',
        currentStatus: 'enforced',
    },
    {
        id: 'ci.publishable-package.requires-changeset',
        title: 'Publishable package changes require a changeset entry',
        category: 'ci enforcement',
        currentType: 'repository-enforced',
        sourceDocument: 'docs/instructions/agentils.instructions.md',
        originalGuidance:
            '每个改动了**可发布**包（`packages/quality-gate/*`、`packages/logger/*` 或 `packages/workflow-sdk/*`）的 PR 必须配套运行 `pnpm changeset`，按交互提示选择受影响的包和 bump 类型（patch / minor / major），生成 `.changeset/<name>.md` 并随 PR 提交。`packages/logger-collector/**` 是 `@agent-ils/logger` 的 release-coupled path，改 collector 也必须给 `@agent-ils/logger` 加 changeset。**CI 只在 PR 上强制检查**（[`.github/workflows/ci.yml`](.github/workflows/ci.yml)）；changesets 生成的 Version PR 合并到 `main` 后不会再要求新增 `.changeset/*.md`。',
        enforcementLevel: 'block',
        enforcementPhase: 'ci',
        enforcementTarget: 'repository-ci',
        applicableRuntime: ['repository'],
        requiredCapabilitiesAll: ['repository-ci', 'pull-request', 'changed-files', 'added-files'],
        checkStrategy: {
            kind: 'changeset-required',
            publishablePackages: ['@agent-ils/quality-gate', '@agent-ils/logger', '@agent-ils/workflow-sdk'],
            releaseCoupledDirs: [{ dir: 'packages/logger-collector', packageName: '@agent-ils/logger' }],
        },
        failureMessage: 'Publishable package changes were detected without a matching changeset entry.',
        fixHint: 'Run `pnpm changeset` and commit the generated `.changeset/*.md` file.',
        currentStatus: 'enforced',
    },
    {
        id: 'git.protected-branch.no-direct-commit',
        title: 'Protected branches cannot be used as direct work branches',
        category: 'git-hook enforcement',
        currentType: 'repository-enforced',
        sourceDocument: 'docs/skills/branch-name-standard/SKILL.md',
        originalGuidance: 'Run `git checkout -b <name>`. Never push directly to `main`.',
        enforcementLevel: 'block',
        enforcementPhase: 'git-hook',
        enforcementTarget: 'repository-git-hook',
        applicableRuntime: ['repository'],
        requiredCapabilitiesAll: [],
        checkStrategy: {
            kind: 'external-script',
            script: 'node scripts/dev/check-branch-for-prd.mjs',
            notes: 'Existing ECAM pre-commit branch guard remains the enforcement entry.',
        },
        failureMessage: 'Protected branch policy is enforced by the branch gate script.',
        fixHint: 'Create a work branch before committing.',
        currentStatus: 'enforced',
    },
    {
        id: 'agent.chat-never-ends-implicitly',
        title: 'Chat must not end implicitly',
        category: 'guidance-only',
        currentType: 'guidance-only',
        sourceDocument: 'README.md',
        originalGuidance:
            'A single LLM invocation must be able to host **multiple rounds** of clarification + tool calls. Anything that silently terminates the chat — finished tool, errored tool, "task done" guess — is a bug. Webview submissions feed back into the same invocation, never dispatch a new one.',
        enforcementLevel: 'warn',
        enforcementPhase: 'guidance',
        enforcementTarget: 'guidance',
        applicableRuntime: ['claude', 'codex', 'copilot'],
        checkStrategy: {
            kind: 'not-machine-checkable',
            reason: 'Conversation lifecycle is controlled outside the local hook payload.',
        },
        failureMessage: 'This rule remains guidance-only.',
        fixHint: 'Review orchestration behavior manually when lifecycle changes are introduced.',
        currentStatus: 'guidance-only',
    },
    {
        id: 'workflow.test-first.before-implementation',
        title: 'Business changes should follow test-first sequencing',
        category: 'guidance-only',
        currentType: 'guidance-only',
        sourceDocument: 'docs/instructions/agentils.instructions.md',
        originalGuidance:
            '顺序固定：(1) 写需求 / 边界条件 → (2) 写 schema 与 I/O 合同 → (3) 写测试用例（含**反向测试** / negative test）→ (4) 才写实现。',
        enforcementLevel: 'warn',
        enforcementPhase: 'guidance',
        enforcementTarget: 'guidance',
        applicableRuntime: ['claude', 'codex', 'copilot'],
        checkStrategy: {
            kind: 'not-machine-checkable',
            reason: 'Commit diffs do not reliably reveal authoring order.',
        },
        failureMessage: 'This rule remains guidance-only.',
        fixHint: 'Review implementation history and test coverage during code review.',
        currentStatus: 'guidance-only',
    },
    {
        id: 'webview.source-of-truth.no-business-state-in-webview',
        title: 'Webview must not self-maintain business state',
        category: 'manual-review',
        currentType: 'manual-review',
        sourceDocument: 'docs/instructions/webview-source-of-truth.instructions.md',
        originalGuidance:
            'webview 路径**禁止**自维护业务 state（如 `interactions[]`、`status` 计算）；只可有 UI 局部 state（composer 草稿、modal 开关、本地 form 校验）',
        enforcementLevel: 'manual-review',
        enforcementPhase: 'manual-review',
        enforcementTarget: 'manual-review',
        applicableRuntime: ['reviewer'],
        checkStrategy: {
            kind: 'not-machine-checkable',
            reason: 'State duplication needs code-structure review and architectural judgment.',
        },
        failureMessage: 'This rule requires manual review rather than a local hook.',
        fixHint: 'Review state ownership during code review or architecture audit.',
        currentStatus: 'manual-review',
    },
]

export function getRulesForPhase(phase) {
    return RULE_REGISTRY.filter((rule) => rule.enforcementPhase === phase)
}
