import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'interaction/index': 'src/interaction/interaction-loop.ts',
    'interaction/sampling': 'src/interaction/sampling-client.ts',
    'interaction/channel-mcp': 'src/interaction/channel-mcp.ts',
    'interaction/channel-hc': 'src/interaction/channel-hc.ts',
    'gateway/index': 'src/gateway/gateway.ts',
    'orchestrator/index': 'src/orchestrator/index.ts',
    'control-plane/index': 'src/control-plane/index.ts',
    'store/index': 'src/store/index.ts',
    'summary/index': 'src/summary/index.ts',
    'control/index': 'src/control/index.ts',
    'audit/index': 'src/audit/audit-logger.ts',
    'budget/index': 'src/budget/budget-checker.ts',
    'policy/index': 'src/policy/tool-policy-checker.ts',
    'config/index': 'src/config/defaults.ts',
    'types/index': 'src/types/index.ts',
  },
  format: ['esm'],
  target: 'node20',
  outDir: 'dist',
  external: [/^node:/, 'express', '@modelcontextprotocol/sdk', 'zod'],
  clean: true,
  sourcemap: true,
  dts: true,
  splitting: true,
  treeshake: true,
  minify: true,
  banner: {
    js: '#!/usr/bin/env node\n// AgentILS MCP Server',
  },
  onSuccess: 'echo "[tsup] Build complete"',
})
